// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v5.29.3

/* eslint-disable */

export * as dietcode from "./index.dietcode.ts";
export * as google from "./index.google.ts";
export * as host from "./index.host.ts";
